apiVersion: apps/v1
kind: Deployment
metadata:
  name: caching-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: caching
  template:
    metadata:
      labels:
        bb: caching
    spec:
      containers:
      - name: caching-apacheignite
        image: apacheignite/ignite
        ports:
        - containerPort: 10800
        - containerPort: 8080
        env:
        - name: OPTION_LIBS
          value: "ignite-rest-http"
      - name: caching-redis
        image: redis:latest
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: caching-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: caching
  ports:
  - name: http
    port: 10800
    targetPort: 10800
    nodePort: 30001
  - name: http1
    port: 6379
    targetPort: 6379
    nodePort: 30002
