services:
  redis:
    container_name: redis_service
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - dapr-network
  ignite:
    container_name: ignite_service
    #image: apacheignite/ignite
    image: gridgain/community:8.9.2
    ports:
      - 10800:10800
    networks:
      - dapr-network
  cacheservice:
    image: springboot-cache-image:latest
    environment:
      REDIS_URL: redis://redis:6379
      IGNITE_URL: ignite:10800
      CACHE_CLIENT: ${CACHE_VALUE}
      CACHE_NAME: ${CACHE_NAME}
      CACHE_REBALANCE_MODE: ${CACHE_REBALANCE_MODE}
      LOGGING_CONFIG: /usr/local/lib/logback.xml
    ports:
      - 7070:7070
    depends_on:
      - redis
      - ignite
    networks:
      - dapr-network
 
  cacheservice-dapr:
    image: "daprio/daprd:1.8.0"
    command: ["./daprd",
     "-app-id", "cacheservice",
     "-app-port", "7070",
     "-placement-host-address", "placement:50006",
     "-components-path", "./components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - cacheservice
      - dapr-placement
    network_mode: "service:cacheservice"

  dapr-placement:
    image: "daprio/dapr:1.8.0"
    command: ["./placement", "--port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - dapr-network

  
networks:
   dapr-network:
