# db deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unleash-db
  labels:
    app: unleash-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unleash-db
  template:
    metadata:
      labels:
        app: unleash-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "db"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust"
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
          exec:
            command:
            - "pg_isready"
            - "--username=postgres"
            - "--host=127.0.0.1"
            - "--port=5432"

---
apiVersion: v1
kind: Service
metadata:
  name: unleash-db
spec:
  selector:
    app: unleash-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: LoadBalancer
