apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: bb-site
        image: europe-west2-docker.pkg.dev/lbg-coe/hello-repo/springboot-cache-image:v3
        env:
        - name: REDIS_URL
          #value: "redis://caching:6379"
          value: "redis://caching-entrypoint:6379"
        - name: IGNITE_URL
          value: "caching-entrypoint:10800"
        - name: CACHE_CLIENT
          value: "IGNITE"
        - name: UNLEASHURL
          value: "http://unleash-web:4242/"
        - name: TOKEN
          value: "c264c3dec7e3ed2fd3ecdac5b9e2ff4c337c44e0670e05e3c53ea93e"
        ports:
        - containerPort: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: bb-entrypoint
  namespace: default
spec:
  type: LoadBalancer
  selector:
    bb: web
  ports:
  - port: 7070
    targetPort: 7070
    nodePort: 30003
status:
  loadBalancer: {}
