# web deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unleash-web
  labels:
    app: unleash-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unleash-web
  template:
    metadata:
      labels:
        app: unleash-web
    spec:
      containers:
      - name: unleash-web
        image: unleashorg/unleash-server:latest
        ports:
        - containerPort: 4242
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:unleash@unleash-db/db"
        - name: DATABASE_SSL
          value: "false"
        - name: LOG_LEVEL
          value: "warn"
        - name: INIT_FRONTEND_API_TOKENS
          value: "default:development.unleash-insecure-frontend-api-token"
        - name: INIT_CLIENT_API_TOKENS
          value: "default:development.unleash-insecure-api-token"
        command: ["node", "index.js"]
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          exec:
            command:
            - "wget"
            - "--no-verbose"
            - "--tries=1"
            - "--spider"
            - "http://localhost:4242/health"
---
apiVersion: v1
kind: Service
metadata:
  name: unleash-web
spec:
  selector:
    app: unleash-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4242
  type: LoadBalancer
